import type { Job } from '@/types/job';

export const mockJobs: Omit<Job, 'id' | 'appliedDate' | 'lastUpdated'>[] = [
  {
    userId: 'mock-user',
    company: 'Google',
    role: 'Senior Software Engineer',
    location: 'Mountain View, CA',
    type: 'full-time',
    status: 'interview',
    salary: '$180,000 - $250,000',
    description:
      'Build scalable systems that serve billions of users worldwide.',
    requirements: [
      'React',
      'TypeScript',
      'System Design',
      'Distributed Systems',
    ],
    notes: 'Great team culture, exciting projects',
    contactPerson: 'Sarah Johnson',
    contactEmail: 'sarah.johnson@google.com',
    jobUrl: 'https://careers.google.com/jobs/123',
    resumeUsed: 'resume-v2.pdf',
  },
  {
    userId: 'mock-user',
    company: 'Meta',
    role: 'Frontend Engineer',
    location: 'Menlo Park, CA',
    type: 'full-time',
    status: 'applied',
    salary: '$160,000 - $220,000',
    description: 'Build the next generation of social technology.',
    requirements: ['React', 'JavaScript', 'GraphQL', 'Mobile Development'],
    notes: 'Applied through referral',
    jobUrl: 'https://careers.meta.com/jobs/456',
    resumeUsed: 'resume-v2.pdf',
  },
  {
    userId: 'mock-user',
    company: 'Netflix',
    role: 'Full Stack Developer',
    location: 'Los Gatos, CA',
    type: 'full-time',
    status: 'phone-screen',
    salary: '$170,000 - $240,000',
    description: 'Help deliver entertainment to 200M+ members worldwide.',
    requirements: ['Node.js', 'React', 'AWS', 'Microservices'],
    notes: 'Phone screen scheduled for next week',
    contactPerson: 'Mike Chen',
    contactEmail: 'mike.chen@netflix.com',
    jobUrl: 'https://jobs.netflix.com/jobs/789',
    resumeUsed: 'resume-v1.pdf',
  },
  {
    userId: 'mock-user',
    company: 'Stripe',
    role: 'Software Engineer',
    location: 'San Francisco, CA',
    type: 'full-time',
    status: 'offer',
    salary: '$175,000 - $230,000',
    description: 'Build financial infrastructure for the internet.',
    requirements: ['Ruby', 'JavaScript', 'APIs', 'Financial Systems'],
    notes: 'Received offer! Need to respond by Friday',
    contactPerson: 'Emily Davis',
    contactEmail: 'emily.davis@stripe.com',
    jobUrl: 'https://stripe.com/jobs/101112',
    resumeUsed: 'resume-v2.pdf',
  },
  {
    userId: 'mock-user',
    company: 'Airbnb',
    role: 'Product Engineer',
    location: 'San Francisco, CA',
    type: 'full-time',
    status: 'rejected',
    salary: '$165,000 - $210,000',
    description: 'Create a world where anyone can belong anywhere.',
    requirements: ['React', 'Python', 'Product Thinking', 'A/B Testing'],
    notes: 'Great interview experience, will apply again in 6 months',
    jobUrl: 'https://careers.airbnb.com/jobs/131415',
    resumeUsed: 'resume-v1.pdf',
  },
];

export const initializeMockData = () => {
  // This function can be called to populate the job store with mock data
  return mockJobs;
};
